
[workspace]
resolver = "2"
members = [
    "cupti",
    "cupti-sys"
, "xtask"]

[workspace.dependencies]
cupti = { version = "0.1.0", path = "cupti" }
cupti-sys = { version = "0.1.0", path = "cupti-sys" }
